[ko]
  title = "쪼식이 블로그"
  languageName = "한국어"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/ko"
  
[en]
  title = "Zzossig's Blog"
  languageName = "English"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/en"