logoText = "Zzo blog"
description = "ìª¼ì‹ì´ ë¸”ë¡œê·¸"
custom_css = []
custom_js = []

# header
homeHeaderType = "text" # text, img, slide

# body
enableBreadcrumb = true
enablePhotoSwipe = true
enableSearch = true
enableGoToTop = true
enableWhoami = true
summaryShape = "classic" # card, classic, compact
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13
paginateWindow = 1

# whoami
myname = "ìµœì„±í™˜"
email = "zzossig@gmail.com"
whoami = "ğŸ“šLearnerğŸ¤“NerdğŸŒWeb Developer"
useGravatar = true
location = "Seoul, Korea"
organization = ""
link = "https://zzossig.io"

# sidebar
enableBio = true
enableSidebar = true
enableSidebarTags = true
enableSidebarSeries = true
enableSidebarCategories = true
enableToc = true
enableTocSwitch = true
itemsPerCategory = 5

# footer
showPoweredBy = true
showFeedLinks = true
showSocialLinks = true
enableLangChange = true
enableThemeChange = true
themeOptions = ["dark", "light", "hacker", "solarized", "custom"]

# service
baiduAnalytics = ""
enableBusuanzi = false
busuanziSiteUV = true
busuanziSitePV = true
busuanziPagePV = true

# comment
enableComment = false
disqus_shortname = ""
commento = false

[gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

[utterances]       # https://utteranc.es/
  owner = "zzossig"              # Your GitHub ID
  repo = "blog"               # The repo to store comments

[gitalk]           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[valine]
  enable = false
  appId = 'ä½ çš„appId'
  appKey = 'ä½ çš„appKey'
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'mm' 
  placeholder = 'è¯´ç‚¹ä»€ä¹ˆå§...'
  visitor = false

[changyan]
  changyanAppid = ""        # Changyan app id             # ç•…è¨€
  changyanAppkey = ""       # Changyan app key

[livere]
  livereUID = ""            # LiveRe UID                  # æ¥å¿…åŠ›

# Isso: https://posativ.org/isso/
[isso]
  enable = false
  scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
  dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[socialOptions]
  email = "mailto:zzossig@gmail.com"
  facebook = ""
  twitter = "https://twitter.com/zzossig"
  github = "https://github.com/zzossig/hugo-theme-zzo"
  stack-overflow = "https://stackoverflow.com/users/11747951/zzossig"
  instagram = ""
  google-plus = ""
  youtube = ""
  medium = ""
  tumblr = ""
  linkedin = ""
  pinterest = ""
  stack-exchange = ""
  telegram = ""
  steam = ""
  weibo = ""
  douban = ""
  csdn = ""
  zhihu = ""

[donationOptions]
  enable = false
  alipay = "" 
  wechat = ""
  paypal = ""
  patreon = ""