logoText = "Zzo"
logoType = "short" # long, short
description = "Ï™ºÏãùÏù¥ Î∏îÎ°úÍ∑∏"
custom_css = []
custom_js = []
useFaviconGenerator = true # https://www.favicon-generator.org/

themeOptions = ["dark", "light", "hacker", "solarized", "kimbie"]
notAllowedTypesInHome = ["contact", "talks", "about", "showcase"]
notAllowedTypesInHomeSidebar = ["about", "archive", "showcase"]
notAllowedTypesInArchive = ["about", "talks", "showcase"]

# header
homeHeaderType = "text" # text, img, slide

# body
enableBreadcrumb = true
enableSearch = true
enableSearchHighlight = true
enableGoToTop = true
enableWhoami = true
summaryShape = "classic" # card, classic, compact
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13
paginateWindow = 1
talksPaginate = 8
talksGroupByDate = "2006"

# whoami
myname = "ÏµúÏÑ±Ìôò"
email = "zzossig@gmail.com"
whoami = "üìöLearnerü§ìNerdüåêWeb Developer"
useGravatar = true
location = "Seoul, Korea"
organization = ""
link = "https://zzossig.io"

# sidebar
enableBio = true
enableSidebar = true
enableSidebarTags = true
enableSidebarSeries = true
enableSidebarCategories = true
enableHomeSidebarTitles = true
enableListSidebarTitles = true
enableToc = true
hideToc = false
enableTocSwitch = true
itemsPerCategory = 5
sidebarPosition = "right"

# footer
showPoweredBy = true
showFeedLinks = true
showSocialLinks = true
enableLangChange = true
enableThemeChange = true

# service
baiduAnalytics = ""
enableBusuanzi = false
busuanziSiteUV = true
busuanziSitePV = true
busuanziPagePV = true

# comment
enableComment = true

[utterances]       # https://utteranc.es/
  owner = "zzossig"              # Your GitHub ID
  repo = "blog"               # The repo to store comments

[socialOptions]
  email = "mailto:zzossig@gmail.com"
  twitter = "https://twitter.com/zzossig"
  github = "https://github.com/zzossig/hugo-theme-zzo"
  stack-overflow = "https://stackoverflow.com/users/11747951/zzossig"
  
[copyrightOptions]
  enableCopyrightLink = true
  copyrightLink = "http://creativecommons.org/licenses/by-sa/4.0/"
  copyrightLinkImage = ""
  copyrightLinkText = "CC BY-SA"